
package hello;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CircleFunctionsService", targetNamespace = "http://hello/", wsdlLocation = "http://localhost:8080/WebServiceExample/circlefunctions/getArea?wsdl")
public class CircleFunctionsService
    extends Service
{

    private final static URL CIRCLEFUNCTIONSSERVICE_WSDL_LOCATION;
    private final static WebServiceException CIRCLEFUNCTIONSSERVICE_EXCEPTION;
    private final static QName CIRCLEFUNCTIONSSERVICE_QNAME = new QName("http://hello/", "CircleFunctionsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/WebServiceExample/circlefunctions/getArea?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CIRCLEFUNCTIONSSERVICE_WSDL_LOCATION = url;
        CIRCLEFUNCTIONSSERVICE_EXCEPTION = e;
    }

    public CircleFunctionsService() {
        super(__getWsdlLocation(), CIRCLEFUNCTIONSSERVICE_QNAME);
    }

    public CircleFunctionsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CIRCLEFUNCTIONSSERVICE_QNAME, features);
    }

    public CircleFunctionsService(URL wsdlLocation) {
        super(wsdlLocation, CIRCLEFUNCTIONSSERVICE_QNAME);
    }

    public CircleFunctionsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CIRCLEFUNCTIONSSERVICE_QNAME, features);
    }

    public CircleFunctionsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CircleFunctionsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CircleFunctions
     */
    @WebEndpoint(name = "CircleFunctionsPort")
    public CircleFunctions getCircleFunctionsPort() {
        return super.getPort(new QName("http://hello/", "CircleFunctionsPort"), CircleFunctions.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CircleFunctions
     */
    @WebEndpoint(name = "CircleFunctionsPort")
    public CircleFunctions getCircleFunctionsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://hello/", "CircleFunctionsPort"), CircleFunctions.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CIRCLEFUNCTIONSSERVICE_EXCEPTION!= null) {
            throw CIRCLEFUNCTIONSSERVICE_EXCEPTION;
        }
        return CIRCLEFUNCTIONSSERVICE_WSDL_LOCATION;
    }

}
